GTA_IM_PKL_KEYPOINTS = ['FACIAL_facialRoot', 'FB_Brow_Centre_000', 'FB_Jaw_000', 'FB_L_Brow_Out_000',
                        'FB_L_CheekBone_000',
                        'FB_L_Eye_000', 'FB_L_Lid_Upper_000', 'FB_L_Lip_Bot_000', 'FB_L_Lip_Corner_000',
                        'FB_L_Lip_Top_000',
                        'FB_LowerLipRoot_000', 'FB_LowerLip_000', 'FB_R_Brow_Out_000', 'FB_R_CheekBone_000',
                        'FB_R_Eye_000',
                        'FB_R_Lid_Upper_000', 'FB_R_Lip_Bot_000', 'FB_R_Lip_Corner_000', 'FB_R_Lip_Top_000',
                        'FB_Tongue_000', 'FB_UpperLipRoot_000', 'FB_UpperLip_000', 'IK_Head', 'IK_L_Foot', 'IK_L_Hand',
                        'IK_R_Foot', 'IK_R_Hand', 'IK_Root', 'MH_L_Elbow', 'MH_L_Knee', 'MH_R_Elbow', 'MH_R_Knee',
                        'PH_L_Foot', 'PH_L_Hand', 'PH_R_Foot', 'PH_R_Hand', 'RB_L_ArmRoll', 'RB_L_ForeArmRoll',
                        'RB_L_ThighRoll', 'RB_Neck_1', 'RB_R_ArmRoll', 'RB_R_ForeArmRoll', 'RB_R_ThighRoll',
                        'SKEL_Head',
                        'SKEL_L_Calf', 'SKEL_L_Clavicle', 'SKEL_L_Finger00', 'SKEL_L_Finger01', 'SKEL_L_Finger02',
                        'SKEL_L_Finger10', 'SKEL_L_Finger11', 'SKEL_L_Finger12', 'SKEL_L_Finger20', 'SKEL_L_Finger21',
                        'SKEL_L_Finger22', 'SKEL_L_Finger30', 'SKEL_L_Finger31', 'SKEL_L_Finger32', 'SKEL_L_Finger40',
                        'SKEL_L_Finger41', 'SKEL_L_Finger42', 'SKEL_L_Foot', 'SKEL_L_Forearm', 'SKEL_L_Hand',
                        'SKEL_L_Thigh', 'SKEL_L_Toe0', 'SKEL_L_UpperArm', 'SKEL_Neck_1', 'SKEL_Pelvis', 'SKEL_ROOT',
                        'SKEL_R_Calf', 'SKEL_R_Clavicle', 'SKEL_R_Finger00', 'SKEL_R_Finger01', 'SKEL_R_Finger02',
                        'SKEL_R_Finger10', 'SKEL_R_Finger11', 'SKEL_R_Finger12', 'SKEL_R_Finger20', 'SKEL_R_Finger21',
                        'SKEL_R_Finger22', 'SKEL_R_Finger30', 'SKEL_R_Finger31', 'SKEL_R_Finger32', 'SKEL_R_Finger40',
                        'SKEL_R_Finger41', 'SKEL_R_Finger42', 'SKEL_R_Foot', 'SKEL_R_Forearm', 'SKEL_R_Hand',
                        'SKEL_R_Thigh', 'SKEL_R_Toe0', 'SKEL_R_UpperArm', 'SKEL_Spine0', 'SKEL_Spine1', 'SKEL_Spine2',
                        'SKEL_Spine3', 'SKEL_Spine_Root']
GTA_IM_NPZ_KEYPOINTS = ['head_center', 'neck', 'right_clavicle', 'right_shoulder', 'right_elbow', 'right_wrist',
                        'left_clavicle', 'left_shoulder', 'left_elbow', 'left_wrist', 'spine0', 'spine1', 'spine2',
                        'spine3', 'spine4', 'right_hip', 'right_knee', 'right_ankle', 'left_hip', 'left_knee',
                        'left_ankle']
